name: Release npm package

on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches: '*'
jobs:
  release:
    name: publish 🚀
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Node.js 🤖
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: build package 📦
        run: yarn build:lib
      - name: semantic-release
        run: yarn semantic-release
        env:
           #TO DO - Not all three tokens *should* be needed
           # NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS }}
           NPM_TOKEN: ${{ secrets.GH_ACCESS }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
